# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/ryan/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
#ZSH_THEME="Soliah"
#Pretty good
#ZSH_THEME="af-magic"
#Like af-magic but inclues host name
#ZSH_THEME="afowler"
#User and host with directory
#ZSH_THEME="alanpeabody"
# This is good
#ZSH_THEME="bira"

# Really liking this one
ZSH_THEME="candy"
# Pretty neat, no time but lots of information
#ZSH_THEME="dpoggi"
# Interesting
#ZSH_THEME="tjkirch"
# pretty good
#ZSH_THEME="xiong-chiamiov-plus"

#
#ZSH_THEME="candy"
#ZSH_THEME="avit"
#ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
   git
   zsh-syntax-highlighting
   zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
# # MacPorts Installer addition on 2017-11-27_at_14:37:08: adding an appropriate PATH variable for use with MacPorts.
export PATH="~/.rd/bin:/Users/ryan/bin:/opt/local/bin:/opt/local/sbin:~/bin:/usr/local/mysql/bin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.
export GRADLE_HOME="/opt/local/share/java/gradle"

#Python3 Path
#export PATH="/Library/Frameworks/Python.framework/Versions/3.9/bin:$PATH"
#export PATH="/Library/Frameworks/Python.framework/Versions/3.10/bin:$PATH"

#tmux attach &> /dev/null

if [[ ! $TERM =~ screen ]]; then
    #exec tmux
fi

export CATALINA_HOME=~/Applications/tomcat
#export JAVA_HOME=`/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
#export JAVA_HOME=`/usr/libexec/java_home -v 13`
#export JAVA_HOME=`/usr/libexec/java_home -v 14`
#export JAVA_HOME=`/usr/libexec/java_home -v 16`
#
##alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8.0_152`"
#alias j13="export JAVA_HOME=`/usr/libexec/java_home -v 13`"
#alias j14="export JAVA_HOME=`/usr/libexec/java_home -v 14`"
#alias j16="export JAVA_HOME=`/usr/libexec/java_home -v 16`"

alias pkb="sudo pkill bluetooth"
alias qsi="ioreg -l -d 1 -w 0 | grep SecureInput"
alias restartBird="killall bird"
alias vcsetup="source /opt/vbcc/envsetup.sh"

# Set VBCC Amiga home
#export VBCC=/opt/amiga/

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/ryan/.sdkman"
[[ -s "/Users/ryan/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/ryan/.sdkman/bin/sdkman-init.sh"

source "/Users/ryan/.sdkman/bin/sdkman-init.sh"

## Greaseweazle binaries add to path
export PATH=~/Library/Python/3.11/bin:$PATH

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/ryan/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)
